JuliaReinforcementLearning/ReinforcementLearning.jl

- src/callbacks.jl
- src/epsilongreedypolicies.jl
- src/helper.jl
- src/learner/mdplearner.jl
- test/epsilongreedypolicies.jl
@findmyway This avoids the subtype macro.
> implement epsilon-greedy policy with parametric type

- examples/prioritized_dqn.jl
- src/Utils/readers_writer_lock.jl
- src/components/agents/q_agent.jl
- src/components/buffers/abstract_buffer.jl
- src/components/buffers/circular_turn_buffer.jl
- src/components/learners/q_learner.jl
This closes https://github.com/JuliaReinforcementLearning/ReinforcementLearning.jl/issues/27
> Prioritized dqn

- .gitignore
- Manifest.toml
- Project.toml
- src/Utils/Utils.jl
- src/Utils/devices.jl
- src/components/approximators/q_approximators/neural_network.jl
- src/components/learners/basic_dqn_learner.jl
- src/extensions/CuArrays.jl
- src/extensions/Flux.jl
- src/extensions/Knet.jl
- src/extensions/Zygote.jl
- src/extensions/extensions.jl
Fix #20 
It seems much easier than I thought to support both Knet and Flux (with Zygote).
I'm not sure if we need to support Flux with Tracker. Let's watch https://github.com/FluxML/Flux.jl/issues/883 and decide later.
Here's a quick demo in case someone else would like to try out.
```julia
using ReinforcementLearning, ReinforcementLearningEnvironments, Flux
env = CartPoleEnv(;T=Float32)
ns, na = length(observation_space(env)), length(action_space(env))
for backend in [:Zygote, :Knet]
for device in [:cpu, :gpu]
agent = Agent(
π = QBasedPolicy(
learner = BasicDQNLearner(
approximator = NeuralNetworkQ(
model = Chain(
Dense(ns, 128, relu; backend=backend),
Dense(128, 128, relu; backend=backend),
Dense(128, na; backend=backend)
),
optimizer = ADAM(),
device = device
),
batch_size = 32, …
```
> Support both Knet and Flux(with Zygote)

- docs/src/a_quick_example.md
- src/components/buffers/circular_array_buffer.jl
- src/components/learners/prioritized_dqn_learner.jl
- src/components/learners/rainbow.jl
- src/extensions/Zygote.jl
- Fix the example to produce the figure.
- Update docs for DQNLearner, PrioritizedDQNLearner, and RainbowLearner.
💔Thank you!
> fix example in doc && update examples

- src/components/buffers/circular_array_buffer.jl
- src/components/learners/rainbow.jl
Change when to use the `Zygote.dropgrad` in `RainbowLearner`.
💔Thank you!
> fix a performance bug in rainbow

- benchmarks/circular_array_buffer.jl
- docs/Manifest.toml
- src/Utils/devices.jl
- src/components/buffers/abstract_buffer.jl
- src/components/buffers/circular_array_buffer.jl
- src/components/learners/basic_dqn_learner.jl
- src/components/learners/dqn_learner.jl
- src/components/learners/prioritized_dqn_learner.jl
- src/components/learners/rainbow.jl
- src/extensions/CuArrays.jl
- src/extensions/Zygote.jl
Attempt to improve the performance of DQN related algorithms.
Ref: https://discourse.julialang.org/t/the-performance-difference-of-transferring-subarray-reshapedarray-array-to-gpu/31303/2?u=findmyway
> update benchmark for circular_array_buffer

- docs/src/index.md
Correct link to ReinforcementLearningZoo.jl
> Fix link in docs/src/index.md

- README.md
Hi @jbrea ,
Hope you like our new website [juliareinforcementlearning.org](https://juliareinforcementlearning.org/) 😀 . It's still WIP. Feel free to add more content at https://github.com/JuliaReinforcementLearning/JuliaReinforcementLearning.github.io!
Here I update the Get Started instructions to make things more simple.
<hr>
By the way, could you also update the website link here?
This domain is currently held by me. But maybe we can transfer it to a more stable one. I remember @ViralBShah once mentioned that maybe JuliaComputing can provide support to hold these Julia organization domains. Not sure if it is still possible now.
> Update README.md & website link

- src/ReinforcementLearningZoo/src/experiments/atari/Dopamine_DQN_Atari.jl
- src/ReinforcementLearningZoo/src/experiments/atari/Dopamine_IQN_Atari.jl
- src/ReinforcementLearningZoo/src/experiments/atari/Dopamine_Rainbow_Atari.jl
- src/ReinforcementLearningZoo/src/experiments/atari/rlpyt_A2C_Atari.jl
- src/ReinforcementLearningZoo/src/experiments/atari/rlpyt_PPO_Atari.jl
Fix the dispatch problem in atari experiments.
> Fix atari experiments

- src/ReinforcementLearningZoo/src/experiments/rl_envs/JuliaRL_QRDQN_Cartpole.jl
See last comment in #263, I have not had a look at why the CI did not report the error yet.
> Add timeperstep hook to qrdqn to fix test error

- src/ReinforcementLearningExperiments/deps/experiments/experiments/DQN/JuliaRL_QRDQN_Cartpole.jl
Things I noticed that concern me a little and I would like to help with :
- Pkg.test() doesn't have any tests
- Documentation and Demonstrations/Tutorials are at very early stages and https://juliareinforcementlearning.org/docs/experiments/ need lot of work imo
- I am not able to setup a development environment like I usually do,
```julia
(ReinforcementLearning) pkg> activate .
(ReinforcementLearning) pkg> instantiate
Updating registry at `~/.julia/registries/General`
ERROR: Unsatisfiable requirements detected for package ReinforcementLearningZoo [d607f57d]:
ReinforcementLearningZoo [d607f57d] log:
├─possible versions are: 0.1.0-0.3.7 or uninstalled
└─restricted to versions 0.4 by ReinforcementLearning [158674fc] — no versions left
└─ReinforcementLearning [158674fc] log:
├─possible …
```
> QRDQN experiment reproducibility fix

- .gitignore
- Manifest.toml
- src/ReinforcementLearningBase/Manifest.toml
- src/ReinforcementLearningCore/Manifest.toml
- src/ReinforcementLearningEnvironments/Manifest.toml
- src/ReinforcementLearningExperiments/Manifest.toml
- src/ReinforcementLearningZoo/Manifest.toml
This should make things easier for first-time developers 
https://github.com/JuliaReinforcementLearning/ReinforcementLearning.jl/pull/294#issue-645267611
cc @ashwani-rathee
> Add Manifest.toml

- .github/pull_request_template.md
- Manifest.toml
- NEWS.md
- docs/Manifest.toml
- docs/homepage/Manifest.toml
- src/ReinforcementLearningEnvironments/Manifest.toml
- src/ReinforcementLearningEnvironments/Project.toml
- src/ReinforcementLearningEnvironments/src/ReinforcementLearningEnvironments.jl
- src/ReinforcementLearningExperiments/Manifest.toml
> Remove GR in RLEnvs

- docs/src/tips.md
> update  tips

- src/ReinforcementLearningCore/src/core/stop_conditions.jl
- src/ReinforcementLearningCore/test/core/stop_conditions_test.jl
> Fix broken test

- src/ReinforcementLearningZoo/src/algorithms/dqns/prioritized_dqn.jl
> Update doc string of PrioritizedDQNLearner

- docs/experiments/experiments/Policy Gradient/JuliaRL_DDPG_Pendulum.jl
- src/ReinforcementLearningZoo/src/algorithms/policy_gradient/ddpg.jl
Algorithm now accommodates continuous multi action spaces
Fix #138
> Expand DDPG to multi action spaces

- docs/src/FAQ.md
happends -> happens
PR Checklist
> correct spelling in FAQ

- src/ReinforcementLearningCore/src/policies/q_based_policies/learners/approximators/neural_network_approximator.jl
- src/ReinforcementLearningZoo/src/algorithms/dqns/common.jl
In CRR algorithms, there exists target actor-critic and online actor-critic. We need a function to synchronize.
> Add copyto function

- NEWS.md
- src/ReinforcementLearningBase/Project.toml
> bump version of RLBae

- NEWS.md
- src/ReinforcementLearningZoo/Project.toml
> bump version of RLZoo

- src/ReinforcementLearningCore/src/policies/q_based_policies/learners/approximators/neural_network_approximator.jl
PR Checklist
Found a spot where the whole expression wasn't dotted so there were still some unnecessary allocations in it. Also saw the docstring was a bit inconsistent with showing default values so added that in also.
> Reduce allocations and update docstring for GaussianNetwork

- src/ReinforcementLearningEnvironments/src/environments/wrappers/wrappers.jl
Have not added any test or documentation for this, should I?
> Add wrapped_env[!] to access env inside wrappers

- docs/experiments/experiments/NFSP/JuliaRL_NFSP_KuhnPoker.jl
- src/ReinforcementLearningZoo/src/algorithms/nfsp/abstract_nfsp.jl
- src/ReinforcementLearningZoo/src/algorithms/nfsp/nfsp.jl
- src/ReinforcementLearningZoo/src/algorithms/nfsp/nfsp_manager.jl
The current implementation of `nfsp` is incorrect since it errored processing some train samples' information for `rl_agent` in some stages.
Here, I correct the update process for `NFSPAgent,` and the experiment's result looks stable for now when the number of train episodes is larger than the epsilon decay step.
> correct `nfsp` implementation

- docs/experiments/experiments/NFSP/JuliaRL_NFSP_KuhnPoker.jl
- src/ReinforcementLearningZoo/src/algorithms/nfsp/nfsp.jl
- src/ReinforcementLearningZoo/src/algorithms/nfsp/nfsp_manager.jl
#439 mentioned that the NFSP experiment's running time is too long.
I've tried to update the experiment's parameters to decrease the running time.
For now, the running time is about 5 min, and the performance looks well.
> update the nfsp experiment's parameters

- docs/src/tutorial.md
line 39
desgin -> design
Looks better 👍🏽
> Tiny text typo

- docs/experiments/config.json
This would disable all notebook generation and thus reduce the generation time from 3x to 2x. A side effect is #421 is no longer an issue (since there's no nbview anymore 😆 )
This requires the master branch of DemoCards (https://github.com/johnnychen94/DemoCards.jl/pull/98) to actually work. Currently, it should not change anything.
It's up to you to decide whether you want to merge it now or then. Both are valid choices from my understanding.
closes #421
> disable notebook generation

- docs/experiments/experiments/Policy Gradient/JuliaRL_MADDPG_KuhnPoker.jl
- docs/homepage/blog/ospp_report_210370190/index.md
- src/ReinforcementLearningCore/src/policies/agents/trajectories/trajectory_extension.jl
- src/ReinforcementLearningZoo/src/algorithms/policy_gradient/maddpg.jl
Add support for the environments of `FULL_ACTION_SET` in **MADDPG**, and update the report.
> Update maddpg and the report

- docs/src/How_to_write_a_customized_environment.md
- src/ReinforcementLearningBase/src/interface.jl
> Chancestyle doc update

- src/ReinforcementLearningCore/src/policies/q_based_policies/learners/approximators/neural_network_approximator.jl
- src/ReinforcementLearningZoo/src/algorithms/offline_rl/CRR.jl
- src/ReinforcementLearningZoo/src/algorithms/offline_rl/FisherBRC.jl
- src/ReinforcementLearningZoo/src/algorithms/offline_rl/PLAS.jl
- src/ReinforcementLearningZoo/src/algorithms/offline_rl/offline_rl.jl
- src/ReinforcementLearningZoo/src/algorithms/policy_gradient/sac.jl
In this PR:
1. Implement FisherBRC algorithm. I test it in Pendulum env, and FisherBRC's performance is better than online SAC. (But it is very slow)
2. Update docs, including CRR, PLAS, and SAC.
3. Fix some bugs.
> FisherBRC algorithm and update docs

- docs/homepage/blog/ospp_report_210370190/index.md
- src/ReinforcementLearningCore/src/policies/q_based_policies/q_based_policy.jl
> Update prob function of `QBasedPolicy.`

- src/ReinforcementLearningZoo/src/algorithms/offline_rl/BEAR.jl
- src/ReinforcementLearningZoo/src/algorithms/offline_rl/common.jl
- src/ReinforcementLearningZoo/src/algorithms/offline_rl/offline_rl.jl
> Update BEAR algorithm

- docs/experiments/experiments/Offline/JuliaRL_BCQ_Pendulum.jl
- docs/experiments/experiments/Offline/JuliaRL_BEAR_Pendulum.jl
- docs/experiments/experiments/Offline/JuliaRL_CRR_Pendulum.jl
- docs/experiments/experiments/Offline/JuliaRL_FisherBRC_Pendulum.jl
- docs/experiments/experiments/Offline/JuliaRL_PLAS_Pendulum.jl
- docs/homepage/blog/phase2_technical_report_of_enriching_offline_reinforcement_learning_algorithms_in_reinforcement_learning_jl/index.md
- src/ReinforcementLearningCore/src/policies/q_based_policies/learners/approximators/neural_network_approximator.jl
- src/ReinforcementLearningZoo/src/algorithms/offline_rl/BCQ.jl
- src/ReinforcementLearningZoo/src/algorithms/offline_rl/BEAR.jl
- src/ReinforcementLearningZoo/src/algorithms/offline_rl/CRR.jl
- src/ReinforcementLearningZoo/src/algorithms/offline_rl/DiscreteBCQ.jl
- src/ReinforcementLearningZoo/src/algorithms/offline_rl/FisherBRC.jl
- src/ReinforcementLearningZoo/src/algorithms/offline_rl/common.jl
> cpu and gpu test

- docs/experiments/experiments/Policy Gradient/JuliaRL_SAC_Pendulum.jl
> Fix random net init in sac example

- NEWS.md
- src/ReinforcementLearningEnvironments/Project.toml
> Bump version

- NEWS.md
- src/ReinforcementLearningEnvironments/Project.toml
- src/ReinforcementLearningEnvironments/src/environments/examples/CartPoleEnv.jl
- src/ReinforcementLearningEnvironments/test/environments/examples/cart_pole.jl
> Fix bug in cart pole float32

- src/ReinforcementLearningBase/src/interface.jl
> Small typo

- src/ReinforcementLearningCore/src/policies/agents/agent.jl
> Fix dummy action for continuous action spaces

- docs/homepage/blog/ospp_final_term_report_210370741/index.md
> Fix typo in ospp_final_term_report_210370741/index.md

- src/ReinforcementLearningCore/src/core/stop_conditions.jl
> Fix documentation typo

- docs/homepage/blog/an_introduction_to_reinforcement_learning_jl_design_implementations_thoughts/index.md
then => than
appxorimator => approximator
> Fix typos in docs

- NEWS.md
- src/ReinforcementLearningCore/Project.toml
- src/ReinforcementLearningCore/src/utils/processors.jl
The fix in #551 doesn't work anymore.
> Rewrite initialization of `StackFrames`

- .cspell/cspell.json
fixes failing cspell check
PR Checklist
> cspell add Optimise

- src/ReinforcementLearningBase/src/interface.jl
- src/ReinforcementLearningCore/src/policies/q_based_policies/explorers/epsilon_greedy_explorer.jl
> created fallback implementation for legal_action_space_mask

- Project.toml
> Tag the latest code as v0.10.1

- src/ReinforcementLearningEnvironments/src/environments/examples/TicTacToeEnv.jl
Two improvements for the tictactoe environment:
- More explicit logging messages
- Fix a type stability bug in `legal_actions_mask`
> Small improvements for TicTacToeEnv

- src/ReinforcementLearningZoo/src/algorithms/policy_gradient/sac.jl
Hey everyone!
I was recently trying to use SAC with the MultiThreadedEnv Wrapper and found that I needed to adapt the Code a little for that to work.
I decided to share my version of sac.jl that now works with "Normal" Envs and the MTE as well.
I will be honest: I am not very experienced with Julia and may have missed some stuff. Also I was not able to properly test the Code inside the ReinforcementLearning.jl repo. It works perfectly when I define a seperate MSACPolicy with these changes in my local project however.
I hope someone can double check my stuff and possibly give me some hints on how to test it myself for later reference.
Also here would be the Code for a Experiment using a MTE (If I havent missed anything):
```
function RL.Experiment(
::Val{:JuliaRL},
::Val{:SAC}, …
```
> Adapted SAC to support MultiThreadedEnv

- Manifest.toml
- src/ReinforcementLearningBase/Project.toml
- src/ReinforcementLearningCore/Manifest.toml
- src/ReinforcementLearningCore/Project.toml
- src/ReinforcementLearningCore/src/ReinforcementLearningCore.jl
- src/ReinforcementLearningCore/src/core/run.jl
- src/ReinforcementLearningCore/src/core/stop_conditions.jl
- src/ReinforcementLearningCore/src/policies/agent.jl
- src/ReinforcementLearningCore/src/policies/learners.jl
- src/ReinforcementLearningCore/src/policies/q_based_policy.jl
- src/ReinforcementLearningCore/src/show.jl
> Add struct view

- src/ReinforcementLearningZoo/README.md
> fixed hyperlink in readme

- docs/src/How_to_use_hooks.md
> Typo in hooks docs

- src/ReinforcementLearningZoo/src/algorithms/tabular/td_learner.jl
NoOp's are not currently handled smoothly
> Fix TD Learner so that it handles MultiAgent/Simultaneous with NoOp

- src/ReinforcementLearningCore/test/utils/networks.jl
- src/ReinforcementLearningZoo/src/algorithms/dqns/basic_dqn.jl
- src/ReinforcementLearningZoo/src/algorithms/dqns/iqn.jl
- src/ReinforcementLearningZoo/src/algorithms/dqns/prioritized_dqn.jl
- src/ReinforcementLearningZoo/src/algorithms/dqns/qr_dqn.jl
- src/ReinforcementLearningZoo/src/algorithms/dqns/rainbow.jl
- src/ReinforcementLearningZoo/src/algorithms/dqns/rem_dqn.jl
- src/ReinforcementLearningZoo/src/algorithms/offline_rl/behavior_cloning.jl
- src/ReinforcementLearningZoo/src/algorithms/offline_rl/ope/FQE.jl
- src/ReinforcementLearningZoo/src/algorithms/policy_gradient/trpo.jl
> import params and gradient

- src/ReinforcementLearningEnvironments/src/ReinforcementLearningEnvironments.jl
- src/ReinforcementLearningEnvironments/src/environments/3rd_party/pettingzoo.jl
- src/ReinforcementLearningEnvironments/src/environments/3rd_party/structs.jl
- src/ReinforcementLearningExperiments/src/experiments/MARL/DQN_mpe_simple.jl
This is the first pull request out of three introducing state of the art multi agent reinforcement learning algorithms. They both include some communication mechanisms for the agents. In order to test algorithms against powerful benchmark environments, this pull request provides the python pettingzoo library bundled into the Julia ReinforcementLearning module.
There are several environments covering a multitude of different assumptions on multi agent scenarios such as cooperation, competition as well as team settings. ([PettingZoo Documentation](https://pettingzoo.farama.org/))
> added pettingzoo and one single agent example

- NEWS.md
- src/ReinforcementLearningZoo/src/algorithms/tabular/td_learner.jl
> Reduce unnecessary array allocations

- src/ReinforcementLearningBase/Project.toml
> Fix compat for RLBase

- src/ReinforcementLearningCore/Project.toml
> Fix RLCore version, prep for bump

- src/ReinforcementLearningEnvironments/Project.toml
> Fix IntervalSets compat for RLEnvironments

- src/ReinforcementLearningExperiments/Project.toml
> Bump RLExperiments, require 0.11

- .github/workflows/ci.yml
> Bump Github Actions cache version

- NEWS.md
- src/ReinforcementLearningCore/src/core/hooks.jl
- src/ReinforcementLearningCore/test/core/hooks.jl
> Add tests, improve performance of RewardsPerEpisode

- src/ReinforcementLearningCore/src/core/hooks.jl
- src/ReinforcementLearningCore/test/core/hooks.jl
> DoEveryNStep tests, performance tweaks

- .github/pull_request_template.md
> Expand PR Template

- src/ReinforcementLearningCore/test/core/hooks.jl
> Add test_noop! to remaining hooks

- src/ReinforcementLearningCore/test/core/hooks.jl
> Make TimePerStep test robust

- Project.toml
> Bump compat of RL.jl to 0.11.0-dev

- NEWS.md
- src/ReinforcementLearningCore/src/policies/agent.jl
- src/ReinforcementLearningCore/test/agent.jl
- src/ReinforcementLearningCore/test/runtests.jl
I'm redoing my previous PR in separate small PRs for easier tracking, and also to work on the upstream and not my RL.jl fork.
PR Checklist
> add kwargs to agent

- docs/src/tips.md
> Add activate_devmode!() explanation to tips.md

- NEWS.md
- src/ReinforcementLearningCore/Project.toml
> Bump RLCore

- .cspell/julia_words.txt
- src/ReinforcementLearningCore/src/policies/agent.jl
- src/ReinforcementLearningCore/src/utils/distributions.jl
- src/ReinforcementLearningCore/src/utils/networks.jl
- src/ReinforcementLearningCore/test/utils/distributions.jl
- src/ReinforcementLearningCore/test/utils/networks.jl
- src/ReinforcementLearningExperiments/deps/experiments/experiments/Offline/GenDataset_SAC_Pendulum.jl
- src/ReinforcementLearningExperiments/deps/experiments/experiments/Offline/JuliaRL_BCQ_Pendulum.jl
- src/ReinforcementLearningExperiments/deps/experiments/experiments/Offline/JuliaRL_BEAR_Pendulum.jl
- src/ReinforcementLearningExperiments/deps/experiments/experiments/Offline/JuliaRL_CRR_Pendulum.jl
- src/ReinforcementLearningExperiments/deps/experiments/experiments/Offline/JuliaRL_FQE_Pendulum.jl
- src/ReinforcementLearningExperiments/deps/experiments/experiments/Offline/JuliaRL_FisherBRC_Pendulum.jl
- src/ReinforcementLearningExperiments/deps/experiments/experiments/Offline/JuliaRL_PLAS_Pendulum.jl
- src/ReinforcementLearningExperiments/deps/experiments/experiments/Policy Gradient/JuliaRL_MPO_CartPole.jl
- src/ReinforcementLearningExperiments/deps/experiments/experiments/Policy Gradient/JuliaRL_PPO_Pendulum.jl
- src/ReinforcementLearningExperiments/deps/experiments/experiments/Policy Gradient/JuliaRL_SAC_Pendulum.jl
- src/ReinforcementLearningZoo/src/algorithms/offline_rl/FisherBRC.jl
- src/ReinforcementLearningZoo/src/algorithms/policy_gradient/mpo.jl
- src/ReinforcementLearningZoo/src/algorithms/policy_gradient/ppo.jl
- src/ReinforcementLearningZoo/src/algorithms/policy_gradient/sac.jl
- src/ReinforcementLearningZoo/src/algorithms/policy_gradient/vmpo.jl
Nothing new compared to #839 It just does not include MPO updates and the content of the other PRs I opened today.
PR Checklist
> Gaussian network refactor and tests

- src/ReinforcementLearningZoo/src/algorithms/policy_gradient/mpo.jl
> Fix a typo in MPO

- NEWS.md
- src/ReinforcementLearningCore/Project.toml
- src/ReinforcementLearningCore/src/core/run.jl
- src/ReinforcementLearningCore/src/policies/agent/multi_agent.jl
- src/ReinforcementLearningCore/src/policies/q_based_policy.jl
- src/ReinforcementLearningCore/src/policies/random_policy.jl
- src/ReinforcementLearningCore/test/policies/multi_agent.jl
- src/ReinforcementLearningEnvironments/Project.toml
- src/ReinforcementLearningEnvironments/src/environments/examples/RockPaperScissorsEnv.jl
- src/ReinforcementLearningEnvironments/src/environments/examples/TicTacToeEnv.jl
- src/ReinforcementLearningEnvironments/test/environments/examples/tic_tac_toe.jl
- src/ReinforcementLearningEnvironments/test/environments/wrappers/wrappers.jl
> Multiplayer Fixes (Clean up errors)

- src/ReinforcementLearningBase/Project.toml
- src/ReinforcementLearningCore/test/policies/multi_agent.jl
> Bump RLBase to v0.11.1

- src/ReinforcementLearningCore/src/core/stop_conditions.jl
- src/ReinforcementLearningCore/test/core/stop_conditions.jl
> Add back ComposedStop

- src/ReinforcementLearningCore/src/core/core.jl
- src/ReinforcementLearningCore/src/core/hooks.jl
- src/ReinforcementLearningCore/src/core/reset_conditions.jl
- src/ReinforcementLearningCore/src/core/run.jl
- src/ReinforcementLearningCore/src/core/stop_conditions.jl
- src/ReinforcementLearningCore/src/policies/agent/multi_agent.jl
> Further refinements

- NEWS.md
- src/ReinforcementLearningCore/src/core/hooks.jl
- src/ReinforcementLearningCore/src/core/run.jl
- src/ReinforcementLearningCore/src/core/stages.jl
- src/ReinforcementLearningCore/src/policies/agent/agent_srt_cache.jl
- src/ReinforcementLearningCore/src/policies/agent/base.jl
- src/ReinforcementLearningCore/src/policies/agent/multi_agent.jl
- src/ReinforcementLearningCore/test/core/hooks.jl
- src/ReinforcementLearningCore/test/policies/agent.jl
- src/ReinforcementLearningCore/test/policies/multi_agent.jl
- src/ReinforcementLearningCore/test/utils/networks.jl
- src/ReinforcementLearningExperiments/deps/experiments/experiments/Offline/JuliaRL_BC_CartPole.jl
- src/ReinforcementLearningZoo/src/algorithms/offline_rl/common.jl
- src/ReinforcementLearningZoo/src/algorithms/policy_gradient/maddpg.jl
- src/ReinforcementLearningZoo/src/algorithms/policy_gradient/trpo.jl
- src/ReinforcementLearningZoo/src/algorithms/policy_gradient/vmpo.jl
- src/ReinforcementLearningZoo/src/algorithms/tabular/double_learner.jl
- src/ReinforcementLearningZoo/src/algorithms/tabular/dyna_agents/dyna_agent.jl
- src/ReinforcementLearningZoo/src/algorithms/tabular/gradient_bandit_learner.jl
- src/ReinforcementLearningZoo/src/algorithms/tabular/monte_carlo_learner.jl
- src/ReinforcementLearningZoo/src/algorithms/tabular/td_learner.jl
> RLCore.update! -> Base.push! API change

- src/ReinforcementLearningEnvironments/Project.toml
> Add compat for CommonRLInterface

- NEWS.md
- src/ReinforcementLearningCore/Project.toml
- src/ReinforcementLearningCore/src/core/hooks.jl
- src/ReinforcementLearningCore/src/core/run.jl
- src/ReinforcementLearningCore/src/policies/agent/multi_agent.jl
- src/ReinforcementLearningCore/test/core/hooks.jl
> Fix hook issues

- docs/src/How_to_implement_a_new_algorithm.md
> Update implement new alg docs

- src/ReinforcementLearningCore/src/core/run.jl
> Bug fix optimise!

- src/ReinforcementLearningZoo/Project.toml
> Bump RLZoo version for NNlib

- src/ReinforcementLearningCore/Project.toml
- src/ReinforcementLearningCore/src/core/run.jl
- src/ReinforcementLearningCore/src/policies/agent/multi_agent.jl
- src/ReinforcementLearningCore/test/core/base.jl
@HenriDeh Not having added a test for this new feature came back to haunt me. This adds a test and fixes a problem with the code.
> Fix Timer bug

- Project.dev.toml
- src/devmode.jl
PR Checklist
This re-enables the opportunity to use devmode.jl and activate_devmode!(). Needed to adjust compat for Project.toml file in main project. **NOTE:** This is not directly done, but have to be manually copied from Project.dev.toml to Project.toml in the root directory!
For devmode.jl, the dependency on ReinforcementLearning is not needed, as there should be as few dependencies as needed. Depending on the whole RL package might in some cases create cyclic dependencies. (IF one wants to include RLExperiments to RL as dependency, but this is just loosely.)
> fixed devmode / project files

- pipeline.yml
> Add Buildkite / GPU tests

- .buildkite/pipeline.yml
- .github/workflows/ci.yml
> Add RLZoo and RLExperiments to Buildkite

- .buildkite/pipeline.yml
- .github/workflows/ci.yml
- src/ReinforcementLearningCore/src/show.jl
- src/ReinforcementLearningEnvironments/Project.toml
- src/ReinforcementLearningEnvironments/test/runtests.jl
- src/ReinforcementLearningExperiments/src/ReinforcementLearningExperiments.jl
> CI Improvements

- .buildkite/pipeline.yml
- .github/workflows/ci.yml
- src/ReinforcementLearningBase/Project.toml
- src/ReinforcementLearningCore/Project.toml
- src/ReinforcementLearningEnvironments/Project.toml
- src/ReinforcementLearningExperiments/Project.toml
> Github Actions Fixes

- src/ReinforcementLearningCore/Project.toml
> Bump RLCore version

- docs/src/How_to_implement_a_new_algorithm.md
> update docs to loop refactor

- src/ReinforcementLearningCore/Project.toml
- src/ReinforcementLearningEnvironments/Project.toml
> Bump RLCore, RLEnv

- src/ReinforcementLearningZoo/src/algorithms/policy_gradient/ppo.jl
Fixes https://github.com/JuliaReinforcementLearning/ReinforcementLearning.jl/issues/1007
PR Checklist
> Fix PPO per #1007

- .devcontainer/Dockerfile
- .devcontainer/devcontainer.json
- .github/workflows/ci.yml
- .github/workflows/cspell.yml
- src/DistributedReinforcementLearning/.github/workflows/ci.yml
- src/ReinforcementLearningBase/Project.toml
- src/ReinforcementLearningBase/src/base.jl
- src/ReinforcementLearningBase/src/space.jl
- src/ReinforcementLearningEnvironments/src/environments/3rd_party/atari.jl
> Add Devcontainer, handle DomainSets 0.7

- .github/workflows/ci.yml
- .gitignore
- src/ReinforcementLearningCore/Project.toml
- src/ReinforcementLearningCore/test/runtests.jl
- src/ReinforcementLearningCore/test/utils/device.jl
- src/ReinforcementLearningCore/test/utils/distributions.jl
- src/ReinforcementLearningCore/test/utils/networks.jl
- src/ReinforcementLearningExperiments/Project.toml
- src/ReinforcementLearningExperiments/deps/experiments/experiments/CFR/JuliaRL_DeepCFR_OpenSpiel.jl
- src/ReinforcementLearningExperiments/deps/experiments/experiments/DQN/Dopamine_IQN_Atari.jl
- src/ReinforcementLearningExperiments/test/runtests.jl
- src/ReinforcementLearningZoo/Project.toml
- src/ReinforcementLearningZoo/test/runtests.jl
> Initial GPUArray transition

- .github/workflows/TagBot.yml
> Update TagBot.yml for subprojects

- src/ReinforcementLearningCore/test/policies/agent.jl
> Fix offline agent test

- .github/workflows/ci.yml
> Swap RLZoo for RLFarm in CI, drop RLExperiments

- src/ReinforcementLearningFarm/Project.toml
> Add missing Flux compat

- .github/workflows/ci.yml
- README.md
- docs/make.jl
- docs/src/tutorial.md
> Fix doc build errors

- src/ReinforcementLearningEnvironments/Project.toml
> Fix RLEnvs version

- .github/workflows/TagBot.yml
> Fix TagBot

- README.md
Right now the homepage of the documentation is not building correctly (see `Project Structure` section: https://juliareinforcementlearning.org/docs/)
I am pretty sure this is just due to an unmatched `  `. This PR hopefully fixes this.  
Note however that I did not build the docs myself to verify.
PR Checklist
> Fix docs homepage

- src/ReinforcementLearningFarm/Project.toml
> Bump RLFarm compat

- src/ReinforcementLearningCore/Project.toml
> Bump RLCore to v0.15.5
