JuliaReinforcementLearning/ReinforcementLearning.jl

- src/ReinforcementLearningEnvironments/src/ReinforcementLearningEnvironments.jl
- src/ReinforcementLearningEnvironments/src/environments/examples/CartPoleEnv.jl
- src/ReinforcementLearningEnvironments/src/environments/examples/MountainCarEnv.jl
- src/ReinforcementLearningEnvironments/src/plots.jl
see https://github.com/JuliaReinforcementLearning/ReinforcementLearning.jl/issues/246
> add plotting for cartpole and mountaincar with Plots.jl

- Manifest.toml
- docs/src/How_to_use_hooks.md
- docs/src/How_to_write_a_customized_environment.md
- src/ReinforcementLearningCore/src/core/hooks.jl
> Improve tutorial

- src/ReinforcementLearningBase/src/interface.jl
Address the concern in https://github.com/JuliaReinforcementLearning/GridWorlds.jl/pull/146#issuecomment-864541170
cc @Sid-Bhatia-0
> Add a warning in docstring of state

- src/ReinforcementLearningBase/src/interface.jl
- src/ReinforcementLearningEnvironments/src/environments/examples/examples.jl
- src/ReinforcementLearningZoo/test/cfr/nash_conv.jl
- src/ReinforcementLearningZoo/test/runtests.jl
Add Base.:(==) and Base.hash for AbstractEnv so that can compute nash_conv on KuhnPokerEnv().
> add Base.:(==) and Base.hash for AbstractEnv and test nash_conv on KuhnPokerEnv

- src/ReinforcementLearningZoo/src/algorithms/policy_gradient/sac.jl
Had some reproducibility issues in my experiments and found that SAC was currently not using its internal rng to sample the actions.
> Make SAC policy use internal rng

- src/ReinforcementLearningEnvironments/src/plots.jl
Added kwargs to plot(env::) for CartPole and MountainCar environments, so the user can control the size, etc. of the output plot. Before
```
plot(::CartPoleEnv; size=(200,200))
```
errored but now works. Same with MountainCarEnv.
> add kwargs to plot(env::)

- src/ReinforcementLearningCore/src/policies/agents/agent.jl
- src/ReinforcementLearningEnvironments/src/environments/wrappers/ActionTransformedEnv.jl
When I want to get the action space of the player 1 with an `ActionTransformedEnv,` it will raise errors like the following:
```Julia
julia> using ReinforcementLearning
julia> env = KuhnPokerEnv();
julia> wrapped_env = ActionTransformedEnv(env);
julia> action_space(wrapped_env, 1)
ERROR: MethodError: no method matching identity(::Base.OneTo{Int64}, ::Int64)
```
Maybe we should move `args...` into the `action_space` function...
> try to fix bugs of ActionTransformedEnv

- src/ReinforcementLearningCore/src/core/experiment.jl
- src/ReinforcementLearningCore/src/extensions/ReinforcementLearningBase.jl
- src/ReinforcementLearningCore/src/policies/q_based_policies/learners/abstract_learner.jl
This is to remove annoying print_tree() deprecation warning.
> add maxdepth kwarg to remove print_tree() deprecation warning

- src/ReinforcementLearningCore/src/policies/q_based_policies/learners/approximators/neural_network_approximator.jl
Found this when looking through PR #497 but not until after it was merged so started this separate one. 
The thing is that the numbers were generated and then converted, and since there exists a `randn(rng, Float32, size)` signature I assumed that would be more efficient.
So there were actually two different calls used in the code, here `f1` and `f2`, and `f3` is the one suggested in this PR. Testing them on small sizes it is almost twice as fast with `f3`, but when reaching larger sizes it actually isn't, and I have no clue why. I think I still prefer this way since it feels like how julia wants it to be done, but if there are a few action dimension and some larger batches are used it could be a loss in speed so maybe it should be considered. Maybe not the most important thing since this …
> More efficient float32 randn

- src/ReinforcementLearningEnvironments/src/converters.jl
`is_discrete_space(1:5)` was not working for me (when I was trying to convert an environment with `discrete2standard_discrete`).
The reason is that 
`typeof([1,2,3]) isa Type{AbstractVector} == false`
`typeof([1,2,3]) isa Type{<:AbstractVector} == true`
Or from the julia manual: https://docs.julialang.org/en/v1/manual/types/#man-typet-type
> `isa(A, Type{B})` is true if and only if A and B are the same object and that object is a type 
PR Checklist
> Fix dispatch for is_discrete_space

- src/ReinforcementLearningEnvironments/src/environments/examples/CartPoleEnv.jl
- src/ReinforcementLearningEnvironments/src/environments/examples/MountainCarEnv.jl
- src/ReinforcementLearningEnvironments/src/plots.jl
Extended the traditional CartPoleEnv to have a continuous option. Also restructured it to be more aligned with the MountainCarEnv.
Edit: Updated the plots for CartPoleEnv and MountionCarEnv. Small changes overall.
> Added a continuous option for CartPoleEnv

- src/ReinforcementLearningCore/src/policies/agents/trajectories/trajectory.jl
- src/ReinforcementLearningZoo/src/patch.jl
Fix warning when calling kwargs.data (at least in Julia 1.7):
`Warning: use values(kwargs) and keys(kwargs) instead of kwargs.data and kwargs.itr`
To reproduce the warning:
Run the tests of ReinforcementLearningCore with Julia 1.7.
PR Checklist
No need!
> Fix warning about kwargs.data

- src/ReinforcementLearningZoo/src/algorithms/tabular/monte_carlo_learner.jl
Since MonteCarloLearner is an AbstractLearner, this empty method is not needed (default behavior of AbstractLearner).
See here:
https://github.com/JuliaReinforcementLearning/ReinforcementLearning.jl/blob/8c0a317e35921c7a989597f87f570f58578fb1cf/src/ReinforcementLearningCore/src/policies/q_based_policies/learners/abstract_learner.jl#L22-L27
> Remove unneeded method

- src/ReinforcementLearningEnvironments/src/environments/3rd_party/AcrobotEnv.jl
- src/ReinforcementLearningEnvironments/src/environments/examples/CartPoleEnv.jl
- src/ReinforcementLearningEnvironments/src/environments/examples/KuhnPokerEnv.jl
- src/ReinforcementLearningEnvironments/src/environments/examples/TinyHanabiEnv.jl
Fix a few issues on the docs page https://juliareinforcementlearning.org/docs/rlenvs/:
1. `AcrobotEnv` was not showing as it was not considered as a valid docstring.
2. Formatting issues with `CartPoleEnv`.
3. The link to `KuhnPokerEnv` was not working as the url for the docstring of a `struct` or `function` is different.
4. The link to `TinyHanabiEnv` was not working as it has not docstring.
> Fix documentation for environments

- src/ReinforcementLearningZoo/src/algorithms/policy_gradient/sac.jl
Hello,
I'm considering using RL.jl to do some research. I'm currently implementing MPO but when I took a look to the implementation of SAC to get a hang of the inner workings of this package, I noticed some docstrings was incomplete. 
Also, when I tried SAC, I found it cumbersome to specify manually the architecture of the target qnetworks even though they are force copied in the constructor anyways. Finally, the possibility of using a warmup policy is nice but if one does not want to, they still have to specify one. So this PR does three things:
1) It defaults the target networks to copies of the qnetworks 
2) It defaults the start_policy to identity if not used and to `policy` if unspecified by the user
3) It adds some additional information in the docstrings.
I'll soon make some other …
> Default qnetwork initializer

- src/ReinforcementLearningZoo/src/algorithms/policy_gradient/td3.jl
PR Checklist
`behavior_actor` respects the user-defined action limit `act_limit`, but `target_actor` was manually set to `1.0f0`.
> using `act_limit` parameter in `target_actor`

- src/ReinforcementLearningCore/test/extensions.jl
This stabilizes the test in two ways: 
- generating Sigma this way ensures a PSD matrix every time
- using Float64 increases the precision to avoid a significant difference. With Float32 I was still getting about 20 fails out of 10000 attempts.
> fix test logdetLorU with Float64

- src/ReinforcementLearningCore/src/policies/agent.jl
When using **AsyncTrajectoryStyle**, _optimise!_ was called with _p_ and _t_ as parameters rather than _policy_ and _trajectory_.
> Fix parameter names for AsyncTrajectoryStyle

- src/ReinforcementLearningCore/src/core/hooks.jl
DoEveryNEpisode hook was called with stage=POST_EPISODE_STAGE as default rather than PostEpisodeStage().
Not sure how this is meant to work in the future, but this is at least a temporary fix.
> Update DoEveryNEpisode hook to new api

- .cspell/julia_words.txt
- src/ReinforcementLearning.jl
- src/devmode.jl
Making contributions to the package is not an easy task due to package requirements. 
A single contribution is likely to span several packages and it would be a cumbersome workflow to make separate PRs in the different packages and wait for a release to be able to continue the PR. Hence, it is preferable to `dev` each package to work with a local version of all packages of the ecosystem. 
However this must be done in a particular order to avoid dependency conflicts, and it is also a long and annoying process to do.
This PR adds a (non-exported) function `ReinforcementLearning.activate_devmode!()`. This will automatically dev all the packages. Essentially, you should do this when you create a new branch for a new PR and voilà, you're good to go. This function imitates the process in the …
> Add a developer mode

- NEWS.md
- Project.toml
In theory, this PR would allow us to tag a `v0.10.2` version of `ReinforcementLearning.jl` which only uses pre-refactor versions of the packages. This should make it possible to consistently tag newer versions of the sub-packages e.g. `ReinforcementLearningBase.jl`, etc. as we work towards shipping a `v0.11` of the overall package.
@findmyway @HenriDeh Thoughts?
> Pin ReinforcementLearning.jl to pre-refactor versions

- src/ReinforcementLearningCore/src/core/hooks.jl
- src/ReinforcementLearningCore/test/core/hooks.jl
> Refactor and add tests to TotalBatchRewardPerEpisode

- src/ReinforcementLearningCore/src/core/hooks.jl
- src/ReinforcementLearningCore/test/core/hooks.jl
Currently, DoEvery hooks trigger at the first step (because `x % 1 == 0`). But unless we want them to trigger every step/episode, we do not want them to trigger at t = 1.
PR Checklist
> DoEvery should not trigger on t = 1

- .github/workflows/ci.yml
Currently CI is setup to only check subpackages in which changes occurred. But a change in RLCore might break algorithms in Zoo, for example. Currently this would not be caught by CI. This tweak should make sure to trigger tests of subpackages if a dependency changed. 
I will make an impactless change to RLCore n the second commit to see if correctly triggers Envs and Zoo tests, it shouldn't trigger Base.
> Tweak CI to check on dep changes

- src/ReinforcementLearningCore/src/policies/agent/multi_agent.jl
- src/ReinforcementLearningCore/src/policies/random_policy.jl
- src/ReinforcementLearningCore/test/policies/multi_agent.jl
This PR addresses an issue with the new version of `MultiAgentPolicy.` When a sequential environment is terminated by not the last but the first or intermediate player, the loop will continue, although the environment is terminated. This is not the expected behavior. I have added changes as well as a unit test for the TicTacToe environment testing this issue.
PR Checklist
> fixed problem with sequential multi agent envs

- docs/src/How_to_implement_a_new_algorithm.md
- src/ReinforcementLearningBase/src/interface.jl
- src/ReinforcementLearningCore/src/policies/agent/base.jl
- src/ReinforcementLearningCore/src/policies/q_based_policy.jl
- src/ReinforcementLearningExperiments/deps/experiments/experiments/DQN/JuliaRL_BasicDQN_CartPole.jl
- src/ReinforcementLearningExperiments/deps/experiments/experiments/DQN/JuliaRL_BasicDQN_MountainCar.jl
- src/ReinforcementLearningExperiments/deps/experiments/experiments/DQN/JuliaRL_BasicDQN_PendulumDiscrete.jl
- src/ReinforcementLearningExperiments/deps/experiments/experiments/DQN/JuliaRL_BasicDQN_SingleRoomUndirected.jl
- src/ReinforcementLearningExperiments/deps/experiments/experiments/DQN/JuliaRL_DQN_CartPole.jl
- src/ReinforcementLearningExperiments/deps/experiments/experiments/DQN/JuliaRL_DQN_MountainCar.jl
- src/ReinforcementLearningExperiments/deps/experiments/experiments/DQN/JuliaRL_IQN_CartPole.jl
- src/ReinforcementLearningExperiments/deps/experiments/experiments/Offline/JuliaRL_BC_CartPole.jl
- src/ReinforcementLearningZoo/src/algorithms/dqns/basic_dqn.jl
- src/ReinforcementLearningZoo/src/algorithms/dqns/dqn.jl
- src/ReinforcementLearningZoo/src/algorithms/dqns/iqn.jl
- src/ReinforcementLearningZoo/src/algorithms/dqns/prioritized_dqn.jl
- src/ReinforcementLearningZoo/src/algorithms/dqns/qr_dqn.jl
- src/ReinforcementLearningZoo/src/algorithms/dqns/rainbow.jl
- src/ReinforcementLearningZoo/src/algorithms/dqns/rem_dqn.jl
- src/ReinforcementLearningZoo/src/algorithms/policy_gradient/mpo.jl
- src/ReinforcementLearningZoo/src/algorithms/policy_gradient/trpo.jl
- src/ReinforcementLearningZoo/src/algorithms/policy_gradient/util.jl
- src/ReinforcementLearningZoo/src/algorithms/policy_gradient/vpg.jl
See #897 for the explanation.
I don't know how this affects current implementations of algorithms but it is likely to fix some rather than break anything.
PR Checklist
> Fix dispatch and update documentation

- src/ReinforcementLearningCore/src/utils/networks.jl
- src/ReinforcementLearningCore/test/utils/networks.jl
- src/ReinforcementLearningZoo/src/algorithms/policy_gradient/mpo.jl
This simply 
- modifies slightly the math of vec_to_tril to create more stable covariance matrices 
- make the upperbound of the dual adaptive to let it be higher when rewards (and thus Q-values) have higher magnitudes.
> couple of improvements to MPO

- src/ReinforcementLearningZoo/src/algorithms/dqns/prioritized_dqn.jl
Fixes #973. (Has been tested with `CUDA.allowscalar(false)`)
Two remarks
1. Currently, k and p' are returned as CuArrays. This does not seem to hamper the algorithm so I've not reverted them back, but if that is an issue it can be changed.
2. I have not included tests in the form of an experiment but simply modified the existing `JuliaRL_PrioritizedDQN_CartPole`. I can add that to the experiments but I think that it will just clutter the RLExperiments package.
> Prioritised DQN GPU

- src/ReinforcementLearningExperiments/deps/experiments/experiments/DQN/JuliaRL_NFQ_CartPole.jl
- src/ReinforcementLearningZoo/src/algorithms/dqns/NFQ.jl
Hi, I implemented NFQ a while ago (#897) and have since noticed some things that could be improved. Changes are summarized below:
1. Use a (state) -> ... -> |action space| structure for the Q-network (rather than (state, single action) -> ... -> value structure and looping over all actions)
2. Explicitly use gradient / optimise instead of Flux.train
3. Rely on the Trajectory controller for sampling rather than sampling inside the optimise! function
In addition to increased uniformity, this also consumes much less memory on the gpu compared to the previous version, which needed to duplicate all input data |action space| times to loop over all actions. The main drawback is that it is less faithful to the original implementation [1].
[1] Riedmiller, M. (2005). Neural Fitted Q Iteration – …
> Nfq refactor

- src/ReinforcementLearningCore/Project.toml
- src/ReinforcementLearningCore/test/environments/randomwalk1D.jl
- src/ReinforcementLearningCore/test/environments/rockpaperscissors.jl
- src/ReinforcementLearningCore/test/environments/tictactoe.jl
- src/ReinforcementLearningCore/test/policies/agent.jl
- src/ReinforcementLearningCore/test/policies/multi_agent.jl
- src/ReinforcementLearningCore/test/runtests.jl
This dependency was making the local testing of RLCore tedious due to compatibility problems. I copied the three environments used in the tests and removed the dependency.
> remove rlenv dep for tests

- src/ReinforcementLearningCore/src/core/stop_conditions.jl
- src/ReinforcementLearningCore/src/policies/learners/abstract_learner.jl
- src/ReinforcementLearningCore/src/policies/learners/td_learner.jl
- src/ReinforcementLearningCore/src/policies/q_based_policy.jl
- src/ReinforcementLearningCore/test/core/stop_conditions.jl
- src/ReinforcementLearningCore/test/policies/learners/abstract_learner.jl
This pull request fixes the abstract_learner for multiplayer games. It adds a new function `forward(learner::L, env::E, player::Symbol)` that takes a learner, environment, and player symbol as arguments and sends the state to `RLCore.forward(Learner, State)`. This ensures that the learner can handle multiplayer games correctly.
It also cleans up a few other minor issues along the way.
> Fix abstract_learner for multiplayer games

- src/ReinforcementLearningEnvironments/src/environments/examples/PendulumEnv.jl
I noticed that the state returned by `state(apendulumenv)` is `[y, x, torque]`. Which does not correspond to the official state: https://www.gymlibrary.dev/environments/classic_control/pendulum/. This simply swaps sin and cos to obtain a correct environment.
> Correct Pendulum x-y coordinates

- src/ReinforcementLearningCore/src/policies/q_based_policy.jl
Makes the QBasedPolicy work with general learner algorithms rather than a highly restrictive TDLearner algorithm.
PR Checklist
> Make QBasedPolicy general for AbstractLearner s
